### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#1]
Add project details in README.md

**Comment by nehal076** [comment]
I would like to take this up. I can add the README.md file.

**Comment by Roshaen** [comment]
Assigned @nehal076

**Comment by pranit9000** [comment]
I would like to take this up.

**Comment by Roshaen** [comment]
Hey @pranit9000 this issue is already assigned
Stay tuned as we will raise more issues by tomorrow

**Comment by pranit9000** [comment]
> Hey @pranit9000 this issue is already assigned Stay tuned as we will raise more issues by tomorrow

Ok I am waiting @Roshaen

**Comment by Roshaen** [comment]
Hey @pranit9000 check out other issues
