### ISSUE TITLE
Make the alert components modular

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#106]
Alert messages and descriptions should be passed through the constructor

**Comment by sarkartanmay393** [comment]
@Roshaen I would like to work on it. And can you tell me a little more about the changes, I've to perform.

**Comment by Bhavikk01** [comment]
What you have to do is you have to make the component dynamic means if someone is using this component then he/she only have to pass the properties or attributes and the desired widget would be delivered. So you have to take properties example title, description, color, etc from constructor and then have to use those values in your code.

**Comment by sarkartanmay393** [comment]
Oh sure, @Roshaen I want to work under JWOC on this issue.

**Comment by Roshaen** [comment]
Ok @sarkartanmay393 
Assigning you
Go through the Contribution guidelines to get started

**Comment by sarkartanmay393** [comment]
@Roshaen Close the issue and set point label on my pr please.
