### ISSUE TITLE
Add title to all component page

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#107]
![Input Bars](https://user-images.githubusercontent.com/58213083/219959263-17df37e4-d9c1-471f-a2dd-7da56c128977.png)

**Comment by Rubyseher** [comment]
I want to fix this issue , I am participating under JWOC. Can you assign me ?

**Comment by Roshaen** [comment]
Sure @Rubyseher 
Assigning you

**Comment by Rubyseher** [comment]
could u explain in detail what to do? @Roshaen

**Comment by Rubyseher** [comment]
im sorry but could u pls assign this to someone else

**Comment by Akashsri3bi** [comment]
I will fix this I guess we need to put titles to each message box type like name , message or description password and then some description

**Comment by Roshaen** [comment]
ok @Akashsri3bi 
Assigning you

**Comment by Roshaen** [comment]
@Akashsri3bi Updates?

**Comment by Akashsri3bi** [comment]
@Roshaen I just was giving my exams just two-three days I fix this!

**Comment by Roshaen** [comment]
Okay
