### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#17]
### Description

+ Update `README.md`.
+ Add [Roshan Kumar](https://github.com/roshaen) as a maintainer in the readme, as it is done in [this](https://github.com/Clueless-Community/web-ui-kit) one.

**Comment by najeebkp** [comment]
Hi @Roshaen please assign this to me

**Comment by Roshaen** [comment]
okay go ahead @najeebkp
