### ISSUE TITLE
Add AppBar Component 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#18]
### Screenshots

![app_bar_3](https://user-images.githubusercontent.com/91759192/195277203-6121ccdc-5704-4697-9847-ff3d44a02061.png)

**Comment by pratikagr** [comment]
pls assign

**Comment by Debajyoti14** [comment]
@pratikagr Assigned it to you

**Comment by Jhalakupadhyay** [comment]
Can you assign it to me please

**Comment by Debajyoti14** [comment]
@Jhalakupadhyay Go for it

**Comment by Jhalakupadhyay** [comment]
@Debajyoti14 can you guide me on which screen you want that appbar

**Comment by Jhalakupadhyay** [comment]
> @Jhalakupadhyay Go for it

can you guide me in screen do you want the appbar  Iam getting a bit confused here
