### ISSUE TITLE
Make a Scrollable Dialog 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#19]
### Description

Build the UI of this scrollable dialog box

### Screenshots

![scrollable_dialog](https://user-images.githubusercontent.com/91759192/195279042-ced34c6b-76ce-47f5-8805-75c6421ae239.png)

**Comment by sagardev2301** [comment]
@Debajyoti14 , Can you assign this to me ?,
and In which screen I have to add this dialog box ?

**Comment by Roshaen** [comment]
@sagardev2301 Yes you can work on that.
You have to create new screen and add the dialog box
Have a look in [contribution](https://github.com/Clueless-Community/flutter-ui-components/blob/master/CONTRIBUTING.md) guide and do accordingly

**Comment by sagardev2301** [comment]
@Roshaen , Is the item in dialog box are selectable ?

**Comment by Roshaen** [comment]
Yes @sagardev2301 
You should also make the widget reusable
