### ISSUE TITLE
Build a Toggle Switch

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#20]
### Description

Build the UI of the Toggle Switch component as shown in the image below

### Screenshots

![toggle_switch](https://user-images.githubusercontent.com/91759192/195279808-4b164b0f-2345-4cb9-beaf-6d08b697d2fe.png)

**Comment by Roshaen** [comment]
@abhishek-900 you are assigned to another issue.
Please check that out
