### ISSUE TITLE
Build a Sign in Button

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#21]
### Description

Build the UI of the Sign in button as shown in the image below

### Screenshots

![sign_in_with_google](https://user-images.githubusercontent.com/91759192/195280350-372348ba-b089-484b-9d66-a8abeaff7552.png)

**Comment by sagardev2301** [comment]
Hey @Debajyoti14, Can you this task to me ?

**Comment by Debajyoti14** [comment]
Sure @sagardev2301, Assigned it you.

**Comment by sagardev2301** [comment]
Hey @Debajyoti14 , :) thanks for merging the PR, 
Here is my Clueless Community Profile Link :  https://www.clueless.tech/profile/admin/92708917
