### ISSUE TITLE
Add Customised Floating Action Button

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#22]
### Description

Build the UI of the Floating Action Button as shown in the image below

### Screenshots

![extended_fab_directions](https://user-images.githubusercontent.com/91759192/195280764-e23cbea3-b3b9-4800-86cd-22383e47a469.png)

**Comment by Anuran12** [comment]
I would like to work on this. Please assign it to me

**Comment by AdiAr11** [comment]
Hi, can I work on this?

**Comment by Debajyoti14** [comment]
@AdiAr11 Go for it

**Comment by pratikagr** [comment]
pls assign

**Comment by AdiAr11** [comment]
@pratikagr Hi, Sorry but i'm working on this

**Comment by Debajyoti14** [comment]
@AdiAr11 What's the update?

**Comment by Perumallpardhiv** [comment]
Can I also try this issue?
If possible pls assign me and merge the good looking among all pr's for this issue

**Comment by AdiAr11** [comment]
@Debajyoti14 Im almost done with this.

**Comment by Debajyoti14** [comment]
@AdiAr11 okay, try to do this fast

**Comment by AdiAr11** [comment]
@Debajyoti14 I have created a PR!
