### ISSUE TITLE
Add Modal Nav Drawer

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#23]
### Description

Build the UI of the Modal Nav Drawer as shown in the image below

### Screenshots

![modal_nav_drawer](https://user-images.githubusercontent.com/91759192/195281347-7c968f6f-0d2d-4189-8238-5c3491715d04.png)

**Comment by abhishek-900** [comment]
Hi, can you assign me this ?

**Comment by Roshaen** [comment]
@abhishek-900 Sure go ahead

**Comment by Perumallpardhiv** [comment]
@Roshaen 
Assign me also, want to try this...

**Comment by Debajyoti14** [comment]
@Perumallpardhiv assigned you

**Comment by Perumallpardhiv** [comment]
@Debajyoti14 
Pls add points to my Clueless profile for this #44 pr 
Clueless profile link : https://www.clueless.tech/profile/admin/96647299
