### ISSUE TITLE
Create Glassmorphism Login UI

### ISSUE THREAD

**Issue by nehal076** [Clueless-Community/flutter-ui-components#3]
Create a Glassmorphism Login UI

Refer to [google](https://www.google.com/search?q=glassmorphism+login+UI) for any login UI which follows the Glassmorphism pattern.

**Comment by AnukirtiYadav** [comment]
Created a Glassmorphism Login Screen UI.

**Comment by sowmiya-venkatesan** [comment]
Hi @Roshaen , I would like to contribute to this issue, much appreciated, if you can assign me this issue!

**Comment by Harsh8833** [comment]
Hey @nehal076 I would like to work on this, could you please assign me this

**Comment by nehal076** [comment]
@Harsh8833 you can start working on it and raise a PR. This issue is open to all.
Thanks! :)
