### ISSUE TITLE
Bottom screen view component

### ISSUE THREAD

**Issue by ashdude1401** [Clueless-Community/flutter-ui-components#31]
### Description

I want to make a template for the bottom sheet form  also with a day picker, please

### Screenshots

![Screenshot_20221015-145424](https://user-images.githubusercontent.com/98846260/195979726-133f9c87-6b5e-4840-b958-86ad52cbe2c5.jpg)

**Comment by ashdude1401** [comment]
please ,assign me this work under hackoctober fest

**Comment by Roshaen** [comment]
Sure go ahead
Follow the contribution guidelines

**Comment by ashdude1401** [comment]
@Roshaen please check I have added the Bottom sheet, but it is showing a conflict, please tell me, if I did something wrong
