### ISSUE TITLE
Individual Design Screen

### ISSUE THREAD

**Issue by sagardev2301** [Clueless-Community/flutter-ui-components#33]
### Description

Design Individual Design UI as Shown in Screenshot below.

![image](https://user-images.githubusercontent.com/92708917/195998884-23af3115-1702-4844-b5d5-a723b60f70f0.png)

User will pass the widget path to individual design screen as string and it should show the preview, code of that widget.
Same user will pass the developer GIT ID as string and it should show the git profile of that developer.

**Comment by Roshaen** [comment]
Go ahead. @sagardev2301 
Follow the figma design for app workflow
