### ISSUE TITLE
Design screen for Profile Screen

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#35]
### Description

Replicate the UI of the following profile screen in Flutter 

### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196031792-657bfa6c-dea7-418f-9708-d8a4dd5eb40b.png)

**Comment by balamurugan213** [comment]
Hi @Debajyoti14, I would like to contribute to this issue, much appreciated, if you could assign me this issue!

**Comment by Debajyoti14** [comment]
@balamurugan213 assigned you

**Comment by progite** [comment]
Hey @Debajyoti14 I am interested in contributing to this. Could you please assign this to me as well ?

**Comment by balamurugan213** [comment]
Hi, I have raised a pull request yesterday for this issue
