### ISSUE TITLE
Create a Showcase Readme

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#36]
Create a readme file where screenshot of all UI is showcased

**Comment by curiousTejas** [comment]
I would like to work on this. Please assign this issue to me!

**Comment by tmsagarofficial** [comment]
@Roshaen HI, I would love to take up this issue and work on it.. Assign it to me if its not yet assigned to anyone yet.

**Comment by Roshaen** [comment]
Go ahead @curiousTejas 
Assigning you
