### ISSUE TITLE
Add Onboarding screen UI 

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#38]
### Screenshots

![image](https://user-images.githubusercontent.com/91759192/196031976-1e180ea9-a534-4eab-8c0b-d7ab475cc9e1.png)

**Comment by sagardev2301** [comment]
Hey @Debajyoti14 , can you assign this task to me ?

**Comment by Debajyoti14** [comment]
@sagardev2301 assigned you
