### ISSUE TITLE
Removing Overflows

### ISSUE THREAD

**Issue by Perumallpardhiv** [Clueless-Community/flutter-ui-components#39]
### Description

In two types of login screen, I found some overflow problems 
Removing those overflows and also
Upper Tab bar is containing back arrow option which is not mentioned in screenshot #18. I will fix this also

### Screenshots

![2](https://user-images.githubusercontent.com/96647299/196032637-67660b0a-30a6-41f9-8f68-1e07ffe201b3.jpeg)
![1](https://user-images.githubusercontent.com/96647299/196032639-02e0b879-3591-419f-8f33-31765fd09b85.jpeg)

https://user-images.githubusercontent.com/96647299/196032642-3fa5de57-c61c-4e1c-991b-fdbf910b8f6e.mp4

**Comment by Perumallpardhiv** [comment]
@Roshaen @Debajyoti14 
If you felt that It is valid bug
pls assign it to me

**Comment by Debajyoti14** [comment]
@Perumallpardhiv Go for it

**Comment by Perumallpardhiv** [comment]
> @Perumallpardhiv Go for it

Once check #41 pr linked by me
