### ISSUE TITLE
Create searchbar

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#4]
Implement a searchbar to find components

**Comment by Subhajitongit** [comment]
@Roshaen Can you assign this to me?

**Comment by Roshaen** [comment]
Sure go ahead @Subhajitongit

**Comment by Roshaen** [comment]
Hey @Subhajitongit 
Any progress?

**Comment by Perumallpardhiv** [comment]
@Roshaen 
If possible assign me this issue, I want to try this
Thank you

**Comment by Roshaen** [comment]
Assigned you @Perumallpardhiv
