### ISSUE TITLE
App Bar : Want to add an App Bar theme 

### ISSUE THREAD

**Issue by ArpitSahu01** [Clueless-Community/flutter-ui-components#42]
### Description

By going through your repo, I find your idea unique and amazing. 
Hence I would like to contribute into this.
I am adding an App Bar theme.
In this theme you can scroll between different tabs.
I used gradient as background ,I hope you would like it.

### Screenshots

![IMG_20221016_195114](https://user-images.githubusercontent.com/73908126/196040892-b251374b-44a0-4818-be54-c4bafbc21c72.jpg)

**Comment by Roshaen** [comment]
Assigned @ArpitSahu01
