### ISSUE TITLE
Design Sign Up UI

### ISSUE THREAD

**Issue by nehal076** [Clueless-Community/flutter-ui-components#5]
Develop a responsive signup UI

## Screenshot
<img height="545" alt="image" src="https://user-images.githubusercontent.com/32421196/194721176-a0477f7c-ae66-4383-bcb9-3cda68922df1.png">

You can also refer to:  [Figma link](https://www.figma.com/file/loZ3kahoZLdOSu1pfMmWnO/Flutter-UI-Collections)

**Comment by AnukirtiYadav** [comment]
Created Sign Up and Login Screen UI.

**Comment by Roshaen** [comment]
This issue is still open 
Anyone who wants to implement there own design are welcome ✨

**Comment by ashdude1401** [comment]
I want to work on this ,please assign me the work under hackoctober fest

**Comment by rimonaldo** [comment]
i would also like to offer a solution, you can assign me also.

**Comment by Roshaen** [comment]
Sure

**Comment by sowmiya-venkatesan** [comment]
Hi @Roshaen, I would like to contribute to this issue, much appreciated, if you can assign me this issue!

**Comment by Jhalakupadhyay** [comment]
I want to design this screen can you assign it to  me

**Comment by Tushar98644** [comment]
if the issue still remains open,kindly assign me ...

**Comment by Roshaen** [comment]
The design is already made
if you can implement any other design then I can assign it @Jhalakupadhyay @Tushar98644

**Comment by Jhalakupadhyay** [comment]
whatever design you want i can implement it and if you want I can make my own design and implement it

**Comment by Roshaen** [comment]
yes @Jhalakupadhyay you can create a UI and post it here first

**Comment by Jhalakupadhyay** [comment]
> yes @Jhalakupadhyay you can create a UI and post it here first

do you want only signup UI or both signing and signup UI
and should I share the figma design of the Ui first

**Comment by Jhalakupadhyay** [comment]
https://www.figma.com/file/zUydpURG8z42A8IfrgtYBO/Untitled?node-id=0%3A1&t=7JXAN45XsXW34d5j-1

Above is the link to figma design of signing page, and if any changes is needed then let me know
