### ISSUE TITLE
Build this login screen & the Welcome screen

### ISSUE THREAD

**Issue by Debajyoti14** [Clueless-Community/flutter-ui-components#54]
#### You have to build this Login Screen UI alongside the welcome screen as in the image below
Refer to this Figma file by @sowmiya-venkatesan
https://www.figma.com/file/P4uC0jmYgUnd10UmANnh7O/Clueless-login?node-id=3%3A2

### Screenshots

![196032154-44392240-61d3-46c1-96e0-fe8d8f3cc695](https://user-images.githubusercontent.com/91759192/196968930-83f01ff3-ae54-4ab3-8b9d-b7b60f6cea7f.png)

**Comment by aman6969** [comment]
please assign this to me

**Comment by Nitin-Singh18** [comment]
Hey, can i work on this?

**Comment by mauryakshitij** [comment]
I would like to work on this issue, can you assign this to me

**Comment by Tushar98644** [comment]
I would like to take up the issue...

**Comment by Roshaen** [comment]
Assigning @mauryakshitij

**Comment by mauryakshitij** [comment]
@Roshaen pls review #69

**Comment by Roshaen** [comment]
sure @mauryakshitij
