### ISSUE TITLE
Develop a simple ListView UI

### ISSUE THREAD

**Issue by nehal076** [Clueless-Community/flutter-ui-components#6]
Develop a responsive Listview UI

## Screenshot
<img height="550" alt="image" src="https://user-images.githubusercontent.com/32421196/194718996-52097eb6-2c80-442f-b2f8-1d0b616f8f7f.png">

You can also refer to:  [Figma link](https://www.figma.com/file/loZ3kahoZLdOSu1pfMmWnO/Flutter-UI-Collections)

**Comment by tanmoy27112000** [comment]
I can take this up

**Comment by Roshaen** [comment]
Sure
Assigning you...

**Comment by ashdude1401** [comment]
i want to work on it ,please assign me this work under hackoctober fest
