### ISSUE TITLE
[UI component] Glassmorphism login

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#63]
### Description

Create a glassmorphism Login page

**Comment by ArpitSahu01** [comment]
Hi @Roshaen 
@ArpitSahu01  here,
Please assign this to me I would like to work upon this issue

**Comment by Roshaen** [comment]
Sure go for it @ArpitSahu01

**Comment by Tushar98644** [comment]
@Roshaen if no one is working on it,can i take up the issue...?

**Comment by ArpitSahu01** [comment]
Hi @Tushar98644 ,
I am currently working on this issue
