### ISSUE TITLE
Develop a product display page UI

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#7]
Create a responsive page to display products in list view

**Comment by tanmoy27112000** [comment]
I an take this up

**Comment by Rajdip019** [comment]
Sure @tanmoy27112000 go ahead.

**Comment by chandansgowda** [comment]
Hey @Debajyoti14 
Shall I take this up ?

**Comment by Debajyoti14** [comment]
@chandansgowda Yup, Go for it

**Comment by chandansgowda** [comment]
Hey @Debajyoti14 
Please review #67 
Thanks

**Comment by Roshaen** [comment]
This issue is still open

**Comment by Tapo41** [comment]
I want to contribute to this
