### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#75]
Create a splash screen for the app
![Splash Screen](https://user-images.githubusercontent.com/58213083/216997919-6d4b27e4-a270-475f-b56c-ca73f0a29345.png)

**Comment by Roshaen** [comment]
Here is the Figma file for reference
https://www.figma.com/file/5qmXvL7Dm3v2pHi12FWnNe/Untitled?node-id=0%3A1&t=cKLkJfUvABMekrgL-0

**Comment by AnubhaSharma2709** [comment]
I can work on this please assign

**Comment by Namya13Jain** [comment]
I want to work on this

**Comment by Uttkarsh-raj** [comment]
Hii, I am really interested in doing this. Can you please assign this to me.

**Comment by Akashsri3bi** [comment]
Guys , Please Checkout PR section once , This issue is already dealt with
