### ISSUE TITLE
[Buttons] Create button designs 

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#77]
Figma link
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=206%3A21325&t=8uVFwLwLdM0rv3Hz-1

**Comment by Akashsri3bi** [comment]
I can work on this please assign

**Comment by Aniket-011** [comment]
I want to work on this issue please assign me this issue.

**Comment by Roshaen** [comment]
Hey @Aniket-011 this issue is already assigned
Check out other issues
