### ISSUE TITLE
[Alerts] Create functional alert UI

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#78]
Figma link:
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=140%3A40485&t=8uVFwLwLdM0rv3Hz-1

**Comment by Akashsri3bi** [comment]
I can work on this

**Comment by Roshaen** [comment]
Assigning @Akashsri3bi
