### ISSUE TITLE
Design Buttons

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#8]
Implement button designs according to [Bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/) design

**Comment by Pavel401** [comment]
Please assign me this issue @Roshaen

**Comment by Roshaen** [comment]
ok @Pavel401 go ahead

**Comment by Pavel401** [comment]
There's already a dart package available for bootstrap buttons. Shall I use it @Roshaen ?
https://pub.dev/packages/bs_flutter_buttons

**Comment by Roshaen** [comment]
As we are trying to create our own UI kit so we have to make something of our own
You can make some buttons design if you have something in your mind

**Comment by Roshaen** [comment]
Hey @Pavel401 any update?

**Comment by sowmiya-venkatesan** [comment]
Hi @Roshaen  I would like to contribute to this issue, much appreciated, if you can assign me this issue!

**Comment by Roshaen** [comment]
Sure @sowmiya-venkatesan 
Assigning

**Comment by Sparsh752** [comment]
@Debajyoti14 Can you explain this issue a bit more?

**Comment by Debajyoti14** [comment]
@Sparsh752 Develop different UI of Button.
You can take inspiration from any community project or stuff

**Comment by Sparsh752** [comment]
@Debajyoti14 Can you assign me this?

**Comment by Debajyoti14** [comment]
@Sparsh752 Go ahead

**Comment by Sparsh752** [comment]
@Debajyoti14 I have added the button. Please add the points
