### ISSUE TITLE
[DOC] Improve README with new features

### ISSUE THREAD

**Issue by Suryansh1720001** [Clueless-Community/flutter-ui-components#99]
Hello admin

## Features I want to add - 
- add contributor details.
- add the contribution guidelines.

These are important features of the readme file of any open-source project. kindly assign me this issue.

**Comment by Roshaen** [comment]
hey @Suryansh1720001 
Contribution guidelines is already present in our repo
you can make changes in it if you have any idea 
and also you can add contributors details in readme
So assigning you

**Comment by Suryansh1720001** [comment]
#102 Close as Completed
